# Dockerfile.nginx
FROM nginx:stable-alpine

# Supprimer la config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copier ta configuration nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copier le contenu du dépôt publié
COPY public /usr/share/nginx/html/

EXPOSE 80

